"""Every number (and paper-attributed claim) shown on a slide, with how to verify it.

`check_all` searches each source PDF's text for the claim's patterns and records
the page(s). When the PDF is not available the claim keeps its `fallback`
evidence (e.g. the arXiv abstract text seen via web search) and is marked
"not page-verified" in qa_report.md. Claims with `show=False` were requested by
the brief but could not be verified and are therefore kept OFF the slides.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import pymupdf


@dataclass
class Claim:
    slide: int
    text: str                    # as displayed on the slide
    paper: str                   # registry key, or "computed"
    patterns: list[str]          # regexes; ALL must match on some page(s)
    fallback: str = ""           # evidence when the PDF is unavailable
    brief_value: str = ""        # value the brief asked for, if it differed
    show: bool = True
    note: str = ""
    # results
    status: str = ""
    pages: list[int] = field(default_factory=list)


N = r"[\s ]*"
DASH = r"[\-–—−–]"
X = r"[×x×]"

CLAIMS: list[Claim] = [
    # --- slide 4: filtered ANN -------------------------------------------------
    Claim(4, "ACORN: predicate-agnostic hybrid search via predicate-subgraph traversal on HNSW", "acorn",
          [r"predicate[\s-]*subgraph", r"predicate[\s-]*agnostic"],
          fallback="arXiv abstract (via web search): 'ACORN introduces the idea of predicate subgraph traversal'"),
    Claim(4, "ACORN: two-hop neighbor expansion", "acorn", [r"two[\s-]*hop"], show=False,
          fallback="NOT FOUND in abstract-level evidence; needs PDF check", note="Dropped from slide text"),
    Claim(4, "FAVOR: 1.3–5× higher QPS at Recall@10 = 95%", "favor",
          [rf"1\.3{X}?{N}(to|{DASH}){N}5{X}", r"95"],
          fallback="arXiv abstract 2605.07770 (via web search): 'FAVOR achieves 1.3× to 5× higher QPS at Recall@10 = 95% than state-of-the-art filter-agnostic methods'"),
    Claim(4, "EMA: 1.68–12.25× speedup over general-filtering ANN methods", "ema",
          [rf"1\.68{X}?{N}({DASH}+|to){N}12\.25"],
          fallback="arXiv abstract 2606.00734 (via web search): 'EMA achieves 1.68x--12.25x speedup over state-of-the-art general filtering ANN methods'"),
    # --- slide 5: our result in context ---------------------------------------
    Claim(5, "Eligible fractions 50/20/10/5/2%", "rsa", [r"Reviewer-controlled live semantic HNSW", r"50%", r"2%"]),
    Claim(5, "Live traversal Recall@50 .9833/.9826/.9794/.9752/.9778", "rsa",
          [r"\.9833", r"\.9826", r"\.9794", r"\.9752", r"\.9778"],
          brief_value="live compiled predicate [0.982, 0.977, 0.973, 0.979, 0.983] (older fixed-postfilter run, removed from the paper)"),
    Claim(5, "2× selectivity-aware over-fetch Recall@50 .7923/.7098/.7180/.7482/.8420", "rsa",
          [r"\.7923", r"\.7098", r"\.7180", r"\.7482", r"\.8420"],
          brief_value="post-filter Recall@50 [0.927, 0.609, 0.396, 0.257, 0.135] (older fixed-postfilter run, removed from the paper)"),
    Claim(5, "At 2% eligibility: 0.978 live vs 0.842 over-fetch; 14.57 ms vs 20.14 ms", "rsa",
          [r"\.9778", r"\.8420", r"14\.57", r"20\.14"], brief_value="0.98 vs 0.13 Recall@50 at 2%"),
    Claim(5, "No over-fetch point within 0.005 recall of live traversal in any of 15 conditions", "rsa",
          [r"within 0\.005", r"15"]),
    # --- slide 6: RSA ----------------------------------------------------------
    Claim(6, "56 B/item", "rsa", [r"56 bytes/item"]),
    Claim(6, "~216 B/predicate", "rsa", [r"about 216 bytes/predicate"]),
    Claim(6, "Recall at 20% retention: 0.337 ours, 0.207 dense, 0.352 PQ64, 0.363 FP32", "rsa",
          [r"0\.337", r"0\.207", r"0\.352", r"0\.363", r"20% (candidate )?retention"]),
    Claim(6, "96–134 ns per predicate invocation", "rsa", [rf"96{DASH}134{N}ns"],
          brief_value="~110 ns per predicate evaluation (older run; current paper reports 96–134 ns)"),
    Claim(6, "44,072 fashion products", "rsa", [r"44,072"]),
    # --- slide 7: negation -----------------------------------------------------
    Claim(7, "NevIR: most IR models perform at or below random ranking on negation", "nevir_repro",
          [r"random"], fallback="arXiv abstract 2502.13506 (via web search): 'NevIR, a benchmark study that revealed most IR models perform at or below the level of random ranking when dealing with negation'"),
    Claim(7, "Listwise LLM re-rankers do best but remain below human performance", "nevir_repro",
          [r"listwise"], fallback="arXiv abstract 2502.13506 (via web search)"),
    Claim(7, "E-SENS score S(d) = s(d,q_target) − β s(d,q_trap); training-free; trap query generated by an LLM", "esens",
          [r"trap", r"training[\s-]*free"],
          fallback="arXiv HTML v1 of 2608.30130 (via web search): 'S(d) = s(d, q_target) − β s(d, q_trap)'; equation number not visible",
          brief_value="schematic s(d)=sim(q+,d) − λ sim(q−,d)"),
    # --- slide 8: SAE ----------------------------------------------------------
    Claim(8, "SAE embeddings used for data diffing, correlations, clustering and retrieval", "sae_embed",
          [r"diffing", r"cluster"], fallback="arXiv abstract 2512.10092 (via web search)"),
    Claim(8, "CL-SR: concept-level sparse retrieval from SAE latents", "sae_dense",
          [r"CL-SR|Concept-Level Sparse Retrieval"], fallback="arXiv abstract 2506.00041 (via web search)"),
    # --- slide 10: canvas / Fashion IQ ------------------------------------------
    Claim(10, "Fashion IQ: relative-caption feedback over three categories (dresses, shirts, tops & tees)", "fashioniq",
          [r"dress", r"shirt", r"relative caption"], fallback="arXiv abstract 1905.12794 (via web search)"),
    Claim(10, "Fashion IQ has about 50k pairs per category", "fashioniq", [r"50k|50,000"], show=False,
          fallback="NOT FOUND. Search summary reports 77,684 images and 60,272 relatively-captioned pairs in total, which contradicts ~50k per category",
          note="Removed from slide pending PDF check"),
    Claim(10, "A CLIP zero-shot baseline reaches about 21% Recall@10", "fashioniq", [r"CLIP"], show=False,
          fallback="NOT IN THIS PAPER (Fashion IQ predates CLIP). Closest found: arXiv:2506.06602 'Zero-shot CLIP … reaches only 20-25% Recall@10 on the FashionIQ benchmark' — a different paper not in the reading list",
          note="Removed from slide; needs a source decision"),
    # --- slide 11: generative retrieval ----------------------------------------
    Claim(11, "CQ-SID: +1.15% GMV in a two-week online A/B test", "cqsid", [rf"1\.15{N}%", r"GMV"],
          fallback="arXiv abstract 2605.14434 (via web search): 'GMV +1.15%, UCTCVR +0.40%'"),
    Claim(11, "CQ-SID: generative channel carries 72.63% of purchases", "cqsid", [rf"72\.63{N}%"],
          fallback="arXiv abstract 2605.14434 (via web search): '50.25% of all exposures, 58.96% of all clicks, and 72.63% of all purchases'"),
    Claim(11, "OneSearch: −75.40% operational expenditure", "onesearch", [rf"75\.40{N}%"],
          fallback="arXiv abstract 2509.03236 (via web search): 'reduces operational expenditure by 75.40%'"),
    Claim(11, "OneSearch: +3.22% orders", "onesearch", [rf"3\.22{N}%"], show=False,
          fallback="Only in a secondary summary (emergentmind.com), not seen in the arXiv abstract",
          note="Removed from slide pending PDF check"),
    # --- slide 12: fusion (computed) -------------------------------------------
    Claim(12, "1/(60+rank): 0.0164, 0.0143, 0.0111, 0.0063 at ranks 1, 10, 30, 100", "computed", [],
          note="Arithmetic, computed in build_deck.py (ROUND_HALF_UP to 4 dp)"),
    Claim(12, "k = 60", "computed", [],
          note="Standard RRF constant from Cormack, Clarke & Büttcher (SIGIR 2009); that paper is not on arXiv and was not verified here"),
    # --- slide 13: production QU -----------------------------------------------
    Claim(13, "GenFacet: +42.0% facet CTR and +2.0% UCVR online", "genfacet", [rf"42\.0{N}%", rf"2\.0{N}%"],
          fallback="arXiv HTML 2603.19665v1 (via web search): 'relative increase of 42.0% in facet Click-Through Rate (CTR) and 2.0% in User Conversion Rate (UCVR)'"),
    Claim(13, "Case-driven framework: Annotator, Optimizer and User agents", "casedriven", [r"Annotator", r"Optimizer"],
          fallback="arXiv abstract 2605.05991 (via web search)"),
    Claim(13, "Nearline 7B query-structure LLM: attribute F1 0.887 → 0.926 over BERT", "casedriven",
          [r"0\.887", r"0\.926"], show=False,
          fallback="UNCONFIRMED: a search summary attributes these to a 7B query-structure LLM, but which paper it came from is unclear",
          note="Removed from slide pending PDF check"),
]


def _norm(t: str) -> str:
    return t.replace(" ", " ").replace("ﬁ", "fi").replace("ﬂ", "fl").replace("-\n", "").replace("\n", " ")


def check_all(papers: dict, root: Path) -> list[Claim]:
    texts: dict[str, list[str]] = {}
    for key, p in papers.items():
        if p.pdf:
            doc = pymupdf.open(root / p.pdf)
            texts[key] = [_norm(pg.get_text()) for pg in doc]
    for c in CLAIMS:
        if c.paper == "computed":
            c.status = "computed"
            continue
        pages = texts.get(c.paper)
        if pages is None:
            c.status = "PDF unavailable; " + ("abstract-level evidence only" if c.fallback and not c.fallback.startswith(("NOT", "UNCONF", "Only", "not seen")) else "unverified")
            continue
        found = set()
        ok = True
        for pat in c.patterns:
            hits = [i + 1 for i, t in enumerate(pages) if re.search(pat, t, re.I)]
            if not hits:
                ok = False
                break
            found.update(hits[:3])
        c.pages = sorted(found)
        c.status = "verified in PDF" if ok else "NOT FOUND in PDF"
    return CLAIMS


def fmt_rrf() -> list[tuple[int, str]]:
    from decimal import Decimal, ROUND_HALF_UP
    return [(r, str((Decimal(1) / Decimal(60 + r)).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)))
            for r in (1, 10, 30, 100)]
