"""Write qa_report.md from what the build actually found."""
from __future__ import annotations

import datetime as dt
from pathlib import Path

from .claims import Claim
from .papers import Paper, is_free, titles_match

RSA_TITLE_NOTE = (
    "The local PDF `papers/Random_Semantic_Algebra_latest.pdf` was **not in the repository**. It was compiled "
    "from the checked-in LaTeX source (`paper/icml/`). Its printed title is **\"Compiled Semantic Predicates for "
    "Approximate Nearest Neighbor Search\"**, not the expected \"Random Semantic Algebra: Compiling Latent Search "
    "Predicates over Low-Bit Substrates\". The running header still reads \"Random Semantic Algebra\". The deck "
    "cites the manuscript as Al-Shater (2026), and all RSA numbers were verified against this compiled PDF.")


def write(path: Path, papers: list[Paper], cands, claims: list[Claim], figure_log, layout_notes: list[str],
          render_notes: list[str]) -> None:
    by = {p.key: p for p in papers}
    L = []
    w = L.append
    w("# QA report: Fashion search, the research landscape\n")
    w(f"_Generated by `build_deck.py` on {dt.date.today().isoformat()}._\n")
    w("## 0. Build environment: read this first\n")
    offline = [p for p in papers if p.key != "rsa" and not p.pdf]
    if offline:
        w(f"**{len(offline)} of {len(papers) - 1} arXiv PDFs could not be downloaded.** The build container's "
          "network policy blocks `arxiv.org` (and `export.arxiv.org`, Semantic Scholar, Hugging Face and alphaXiv). "
          "Every request returned `403 CONNECT tunnel failed`. As a result:\n")
        w("- Titles and IDs were verified with **web search results that point at the arXiv abstract pages**, "
          "not by opening the pages.")
        w("- **Licenses could not be read** and are recorded as `unknown`. Under the brief's rule, every external "
          "figure is therefore *internal use only* until its license is checked.")
        w("- Figures from these papers are **labeled placeholders**. No substitute figures were used.")
        w("- Numbers from these papers were checked against the **arXiv abstract text quoted in search results**. "
          "They are marked `abstract-level evidence only`, with no page number. Numbers with no primary-source "
          "evidence were **removed from the slides** (§3).\n")
        w("**To finish the job:** allow `arxiv.org` in the environment's network settings, then run "
          "`python build_deck.py`. The same script downloads the PDFs, reads the licenses, crops the figures, "
          "re-checks every number against the PDF text with page numbers, and regenerates this report.\n")
    w("## 1. Papers: title check, ID corrections, licenses\n")
    w("| Key | arXiv ID | Title check | PDF | License | Source of license |")
    w("|---|---|---|---|---|---|")
    for p in papers:
        tc = "match" if titles_match(p.title, p.expected_title) else "**MISMATCH** (see note)"
        if p.key == "rsa":
            tc = "**MISMATCH**: printed title differs (see note)"
        idn = p.arxiv or "local"
        if p.id_note:
            idn += f" ({p.id_note})"
        w(f"| {p.key} | {idn} | {tc} | {p.pdf_status or '-'} | {p.license} | {p.license_source} |")
    w("")
    w("**Notes**\n")
    w(f"- rsa: {RSA_TITLE_NOTE}")
    for p in papers:
        if p.key != "rsa" and not titles_match(p.title, p.expected_title):
            w(f"- {p.key}: the brief's title was \"{p.expected_title}\". The arXiv title is \"{p.title}\".")
    w("- acorn (2403.04871) and fashioniq (1905.12794) came from memory. Both IDs are **correct**: search "
      "results show the matching titles at those abstract URLs.")
    w("- favor and ema had no ID in the brief. Title search gave favor = 2605.07770 and ema = 2606.00734.\n")

    w("## 2. Figures used, with licenses\n")
    w("| Slide | Paper | Figure | File | License | External sharing |")
    w("|---|---|---|---|---|---|")
    for n, key, label, f, lic in figure_log:
        p = by[key]
        ok = "OK (with attribution)" if is_free(p) else ("n/a (placeholder)" if f == "PLACEHOLDER" else "**needs permission**")
        w(f"| {n} | {key} | {label} | {f} | {lic} | {ok} |")
    w("")
    w("### Needs permission before external sharing\n")
    need = sorted({key for _, key, _, f, _ in figure_log if not is_free(by[key])})
    if need:
        for key in need:
            p = by[key]
            w(f"- **{key}** ({p.arxiv}): license `{p.license}`. Slides that show a real crop carry the footer "
              "\"Internal use only. Figure © the authors.\"")
    else:
        w("- none")
    w("")
    w("### Figures not located (placeholders in the deck)\n")
    for n, key, label, f, lic in figure_log:
        if f == "PLACEHOLDER":
            w(f"- Slide {n}: **{key}**: wanted \"{by[key].want}\". Reason: {by[key].pdf_status}.")
    w("")
    w("### Candidate crops\n")
    w(f"{len(cands)} candidate crops were extracted (see `figures/contact_sheet.html` and `figures/manifest.csv`).")
    flagged = [c for c in cands if c.flag]
    for c in flagged:
        w(f"- ⚠ {c.paper} {c.label}: {c.flag}")
    w("- rsa Figure 4 (candidate-budget frontier) is extracted **but not shown**. In the compiled PDF all "
      "series are drawn in black and the legend overlaps both panels, so the curves cannot be told apart. "
      "Fix this in `paper/icml/sections/07_results_c.tex` (pgfplots `cycle list`/legend position); we may "
      "not alter the figure.")
    w("- rsa Figure 1 is used as is. In the paper's TikZ, the vertical connector from the program store "
      "crosses the text of the \"Universal item code\" box. This is also worth fixing in the paper source.\n")

    w("## 3. Every number and paper-attributed claim on the slides\n")
    w("| Slide | Shown on slide | Source | Status | Page(s) | Brief asked for | Evidence / note |")
    w("|---|---|---|---|---|---|---|")
    for c in claims:
        shown = c.text if c.show else f"~~{c.text}~~ (NOT SHOWN)"
        pages = ", ".join(map(str, c.pages)) or "-"
        ev = c.fallback if (c.status.startswith("PDF unavailable") or not c.status.startswith("verified")) else ""
        ev = "; ".join(x for x in (ev, c.note) if x)
        w(f"| {c.slide} | {shown} | {c.paper} | {c.status} | {pages} | {c.brief_value or '-'} | {ev or '-'} |")
    w("")
    w("### Mismatches between the brief and the source\n")
    for c in claims:
        if c.brief_value:
            w(f"- Slide {c.slide}: brief said **{c.brief_value}**; the deck uses **{c.text}** (source: {c.paper}, "
              f"p. {', '.join(map(str, c.pages)) or 'n/a'}).")
    w("- Slide 5 callout: brief said \"0.98 vs 0.13 Recall@50 at 2% eligibility\". The current Table 7 compares "
      "live traversal with a *2× selectivity-aware over-fetch*, not a fixed post-filter, and gives **0.9778 vs "
      "0.8420**. The fixed post-filter numbers (0.927 → 0.135) are gone from the paper. Commit 698e582 replaced "
      "them as \"confounded systems claims\".")
    w("- Slide 7 equation 11: the brief's schematic `sim(q+,d) − λ sim(q−,d)` was replaced by the E-SENS form "
      "`S(d) = s(d, q_target) − β s(d, q_trap)`, as quoted from the arXiv HTML. **The equation number could not "
      "be confirmed** without the PDF. The schematic is still rendered as `equations/eq11s_esens_schematic.*` "
      "but is not used on the slides.\n")
    w("### Removed from the slides pending verification (your decision)\n")
    for c in claims:
        if not c.show:
            w(f"- Slide {c.slide}: \"{c.text}\". {c.fallback}")
    w("")

    w("## 4. Reading-list links (slide 17)\n")
    w("Each link is `https://arxiv.org/abs/<id>`. arxiv.org is blocked here, so links could not be opened "
      "directly. Each ID→title pair was confirmed from search results that list that exact abs URL with the "
      "expected title:\n")
    for p in papers:
        if p.arxiv:
            w(f"- [{p.short}]({p.abs_url}): \"{p.title}\"")
    w("")
    w("## 5. Visual QA\n")
    for n in render_notes:
        w(f"- {n}")
    for n in layout_notes:
        w(f"- {n}")
    w("")
    w("## 6. Decisions needed from you\n")
    w("1. **Network access:** allow `arxiv.org` so the build can fetch PDFs, licenses and real figures, then rerun "
      "`python build_deck.py`.")
    w("2. **RSA title:** the manuscript is now titled \"Compiled Semantic Predicates for Approximate Nearest "
      "Neighbor Search\". Should the deck keep the RSA name?")
    w("3. **Slide 5 story:** the brief's 0.98 vs 0.13 contrast is no longer in the paper. The slide now shows the "
      "reviewer-controlled 0.978 vs 0.842 result.")
    w("4. **Removed numbers** (§3): Fashion IQ ~50k/category, CLIP ~21% R@10, OneSearch +3.22% orders, and "
      "nearline 7B F1 0.887 → 0.926. Restore them only after the PDF check.")
    w("5. **External sharing:** every external figure needs a license check first (§2).")
    path.write_text("\n".join(L) + "\n", encoding="utf-8")
